### ISSUE TITLE
Issue with Yoshi778 merge

### ISSUE THREAD

**Issue by ghost** [winiciuscota/OG-Bot#27]
Hello,

I try to take the Yoshi update and it seems to work very well until the bot stop for no reason after few seconds.

![image](https://user-images.githubusercontent.com/29168389/28210793-83e7a28e-6899-11e7-97b5-6133d38cf120.png)

I don't know if yoshi will have a look to this, I don't know how to contact him. 

Edit : i just found why after looking for loop setup, it was on false... 

Regards,

**Comment by winiciuscota** [comment]
Great to hear that you have already found a solution.

for future problems that are related to Yoshi's code you can create an issue on this repo https://github.com/yosh778/OG-Bot.

I haven't merged his code yet because I didn't have time to review and test it, also, in a first glance I saw a lot of unnecessary renames
